import mongoose from "mongoose";

const applicantSchema = mongoose.Schema(
    {
     job_id:{
        type:String,
        required:[true, "The Job ID is required"]
     },
     name:{
        type:String,
        required:true,
        lowercase:true,
     },
     email:{
        type:String,
        required:true,
        unique:[true,"The email id has the unique."],
        lowercase:true
     },
     resume:{
        required:true,
     }
    }
    ,{timestapes:true}
    //  i have not created id because auto generated by mongodbId
)

const Applicant = mongoose.model("Applicant",applicantSchema)
