import mongoose from "mongoose";

const jobSchema = mongoose.Schema(
    {
     title:{
        type:String,
        required:true
     },
     description:{
        type:String,
        required:true
     },
     location:{
        type:String,
        required:true
     },
     company_name:{
        type:String,
        required:true
     },
    //  i have not created id because auto generated by mongodbId
    }
    ,{timestapes:true})

const Job = mongoose.model("Job",jobSchema)